# Generated by Django 5.1.7 on 2025-04-14 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
