# Generated by Django 5.1.7 on 2025-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_delete_contactus_remove_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
