# Generated by Django 5.1.7 on 2025-04-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_feedback_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
