# Generated by Django 5.1.7 on 2025-04-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_alter_feedback_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
